### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by kkir** [ryanfchase/wine_app#4]
Basic Models:
- Breakpoint
- User
- Tag (Label?)

**Comment by ryanfchase** [comment]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/6414668/50162332-f2976680-0292-11e9-976c-5bf254029f5e.png">

These are the columns (and a few rows) from the actual spreadsheet I'm using. It would seem that a Breakpoint might encapsulate a new "row" in my spreadsheet. I think the big question about Breakpoints is: do we want it to represent a point in time? Or do we want it to represent a span of time?

Tags/Labels seem like a "thing" that you work on (e.g. Stories from spreadsheet). I think this logically works ... especially if User wants to customize what "things" they're working on.

**Comment by kkir** [comment]
I think these kinds of models can solve the basic requirements

### Breakpoint
| prop |  type | is required
| ------- | -- | - |
| id | ID | true |
| timestamp | ISO8061 | true |
| comment | String | false |
| tags | [Tag] | true |

### Tag
| prop |  type | is required |
| ------- | -- | - |
| id | ID | true |
| label | String | true |
| description | String | false |

two breakpoints (*B1* and *B2*) create an **event**:
### Event
| prop |  type | is required | comment | 
| ------- | -- | - | - |
| id | ID | true |
| start | Breakpoint | true |
| end | Breakpoint | true |
| duration_seconds | Int | true | `B2.timestamp - B1.timestamp`

**Comment by ryanfchase** [comment]
we're going to have a lot of events!

**Comment by ryanfchase** [comment]
@kkir wouldn't it make more sense to apply a label to an event? a breakpoint seems like it should be agnostic to what you're breaking from. When an event object is created, you're applying a meaning to a set of 2 (or more???) breakpoints - thus requiring a Tag/Label
